CREATE TABLE PRODUCT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL,
    PRICE BIGINT NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    IMAGE VARCHAR(80)
);

CREATE TABLE SITEUSER(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL,
    PASSWORD VARCHAR(80) NOT NULL
);